### ISSUE TITLE
Adicionar jekyll-seo-tag para todos os sites da WebIWG

### ISSUE THREAD

**Issue by Dkmister** [webiwg/webiwg-issues#11]
Usar como referência https://github.com/jekyll/jekyll-seo-tag

**Comment by fititnt** [comment]
Estou vendo que este issue vai puxar uma penca de decisões de negócio aqui. As configurações em https://github.com/jekyll/jekyll-seo-tag acabam induzindo a gente a resolver a conta do Twitter e a conta do Facebook.

Outro ponto: o realmente ideal é que aca autor tenha uma imagem para ser usada na hora de compartilhar

---

And you have the following in _data/authors.yml:

``` ruby
benbalter:
  picture: /img/benbalter.png
  twitter: jekyllrb

potus:
  picture: /img/potus.png
  twitter: whitehouse
```

---

Se estamos preocupados com compartilhamento em rede social também, o ideal seria ter foto de autor de cada artigo, ou então forçar autor como se fosse o tradutor principal. Mas isto é algo para alguma discussão futura.

**Comment by fititnt** [comment]
Essa adição deu uma quebrada no rodapé do site, e agora fica aparecendo a string `{"twitter"=>"webiwg"}`. Como já temos que resolver o rodapé na #9, vou aproveitar pra fechar as duas coisas ao mesmo tempo, mas já vou considerar esse issue encerrado por aqui.

Tem **várias** melhorias que podemos fazermos, mas talvez valha a pena abrir em tópicos diferentes pra isso
