### ISSUE TITLE
Google Analytics e Google Web Developer para todos os sites da WebIWG

### ISSUE THREAD

**Issue by Dkmister** [webiwg/webiwg-issues#12]
- [x] Criar conta do Google Analytics;
- [x] Adicionar todos os membros do GT na conta do GA
- [x] Adicionar código de trackeamento do GA em todos os sites
- [x] Preparar conta no Google Webmasters e vincular com GA

**Comment by fititnt** [comment]
Feito. Olhem nos domínios abaixo para terem acesso aos dados:
- https://analytics.google.com/analytics/
- https://www.google.com/webmasters/

---

@Dkmister por algum motivo bizarro, eu consegui adicionar todos no GA e no Web Developer (que agora se chama "Search Console") na hora de adicionar o seu usuário, a conta de gmail que você usa aparece como "esta não é uma conta do Google" mesmo o dominio sendo @ gmail.
