### ISSUE TITLE
Adicionar robots.txt em todos os sites da organização

### ISSUE THREAD

**Issue by fititnt** [webiwg/webiwg-issues#14]
Todos os sites da organização estão sem um arquivo robots.txt na raiz do site. É preciso adicionar na raiz do site um que permita todas as pastas serem crawleadas para todos os os mecanismos de busca, conforme https://developers.google.com/webmasters/control-crawl-index/docs/robots_txt?hl=pt-br.

Com exceção do site da organização em [webiwg/webiwg.github.io](https://github.com/webiwg/webiwg.github.io), o eventos-web, acessibilidade-web-pt e  historia-web-pt também é necessário adicionar também referência no robots URL o sitemap, que deve ter URL completa para o arquivo de robots. 

Um exemplo completo disso, para o site de eventos, seria:

```
User-agent: *
allow: /

sitemap: http://eventos.webiwg.org/sitemap.xml
```

O acessibilidade-web-pt e o historia-web-pt a URL do sitemap deve ser alterada. O webiwg.github.io não tem sitemap e pode ser só omitida.

---
## Tarefas
-  [x] robots.txt adicionado em https://github.com/webiwg/acessibilidade-web-pt
-  [x] robots.txt adicionado em https://github.com/webiwg/eventos-web
-  [x] robots.txt adicionado em https://github.com/webiwg/historia-web-pt
-  [x] robots.txt adicionado em https://github.com/webiwg/webiwg.github.io (sem sitemap)

**Comment by Dkmister** [comment]
@thiamsantos foi responsável por grande parte desta contribuição.
Acho que podemos fechar este issue, qual a sua opinião @fititnt ?

**Comment by fititnt** [comment]
O @thiamsantos fez mensagem de _pull request_ melhor do que a maioria das pessoas no Github. Ele fez relação entre repositórios diferentes e não só colocou hashtag+numero, como também colocou no texto com mensagem do issue original

```
Veja [Adicionar robots.txt em todos os sites da organização](https://github.com/webiwg/webiwg-issues/issues/14)
```

**Comment by thiamsantos** [comment]
A parte de referência à issue no commit foi dica do @Dkmister.

**Comment by fititnt** [comment]
Não é sobre a referência no commit, mas a mensagem do _pull request_. Pode ver, a maioria das pessoas no Github até deixa corpo do Pull Request sem descrição. Você até fez mais do que apenas colocar hashtag pra um issue.

Ficou até melhor do que o Vilmar e eu faríamos.

**Comment by anabastos** [comment]
@thiamsantos muito obrigado pela sua primeira contribuição na IWG! São pessoas como você que fazem diferença!
