### ISSUE TITLE
Traduções via WebIWG para o Rails Girls Guides / Maujor & Marina Flessa

### ISSUE THREAD

**Issue by Dkmister** [webiwg/webiwg-issues#27]
Aqui estão os seguintes traduções que faremos até 10/10:
- [ ] alternative-dev-environment.markdown  [https://github.com/Maujor/railsgirlsguides/blob/gh-pages/_posts/2014-03-24-alternative-dev-environment.markdown](url)
- [x] bundlerfordevelopment.markdown  [https://github.com/Maujor/railsgirlsguides/blob/gh-pages/_posts/2013-07-23-bundlerfordevelopment.markdown](url)
- [ ] ruby-atm.markdown [https://github.com/Maujor/railsgirlsguides/blob/gh-pages/_posts/2014-05-10-ruby-atm.markdown](url)
- [x] continuous-snap-ci.markdown [https://github.com/Maujor/railsgirlsguides/blob/gh-pages/_posts/2015-09-11-continuous-snap-ci.markdown](url)
- [x] twitter-widget.markdown [https://github.com/Maujor/railsgirlsguides/blob/gh-pages/_posts/2016-08-12-twitter-widget.markdown](url)

**Comment by Dkmister** [comment]
Recebi a seguinte mensagem do Maujor:

> "Olá Vilmar,
> Aqui é o Maujor
> 
> Boa Noite
> Uauuuu! Sejam bem-vindos Grupo WebIWG
> 
> Muito obrigado pela super-generosa disposição de vocês em colaborar.
> 
> A tradução do(s) tutorial(ais) já está(ão) reservada(s) para vocês (exceto o documento 2013-08-12-guide-to-the-guide.markdown)  e o nome do Grupo  já consta da planilha de tradutores em: 
> 
> https://docs.google.com/spreadsheets/d/1Gn1BHxwdX3nHyiIDnY1L8ZdNuRJuNhPKli-uG9XWo9c/edit?usp=sharing
> 
> ---
> 
> ATENÇÃO: O documento 2013-08-12-guide-to-the-guide.markdown ACABA DE SER RESERVADO PARA TRADUÇÃO POR OUTRO COLABORADOR
> 
> ---
> 
> Algumas observações sobre as traduções:
> 
> 1) As ocorrências da palavra "guide" nos documentos devem ser traduzidas como "tutorial", salvo em raríssimas exceções
> onde fique evidente que "guia" é o termo mais apropriado.
> 
> 2) Onde houver crédito ao criador do tutorial acrescentar o crédito a você como tradutor(a) conforme exemplo a seguir:
> 
> _Criado por Floor Drees, [@floordrees](https://twitter.com/floordrees)_  (line-break: dois espaços)
> _Traduzido por SEU_NOME, [@seu_nome](https://twitter.com/seu_nome)_ 
> 
> (se preferir pode lincar para qualquer outro perfil seu que não seja o twitter)
> 
> 3) No topo do arquivo da tradução  onde constam os dados YAML, traduza apenas  o dado "title", por exemplo:
> 
> ---
> 
> layout: default
> title: Continuous Deployment - cuz less hassle (<= Traduza somente aqui)
> 
> ## permalink: continuous-travis
> 
> Vá em frente!
> 
> Qualquer dúvida sobre a tradução e-mail para (para Marina e cópia Maujor).
> Por favor acuse recebimento com reply all para (para Marina e cópia Maujor).  
> 
> Grande abraço
> "
> Maurício "Maujor®" Samy Silva

**Comment by fititnt** [comment]
Em https://github.com/webiwg/railsgirlsguides foi criado um branch para cada issue. Quem for commitar, por favor, faça no respectivo branch, não commita no gh-pages, para poder fazer o PR de forma mais suave

**Comment by anabastos** [comment]
Chateada que o guide-to-guide foi pego :(
Depois vamos solicitar mais alguns?

**Comment by fititnt** [comment]
Ana, acho melhor a gente terminar esses primeiros. Eu vou pegar o de CI. Se realmente prefere outro, fala com Vilmar que ele troca

**Comment by fititnt** [comment]
Das solicitadas, o grupo fez três traduções e devolveu as demais por falta de tempo.
- https://github.com/railsgirlsmaceio/railsgirlsguides/pull/11 (@fititnt)
- https://github.com/railsgirlsmaceio/railsgirlsguides/pull/12 (@Dkmister)
- https://github.com/railsgirlsmaceio/railsgirlsguides/pull/15 (@robsmayer)

Caso alguém tenha tempo de fazer outras traduções, pode entrar em contato com ele novamente e reabrir esse issue aqui. Preferimos devolver as outras duas traduções por não ter certeza que seriam feitas rapidamente.

> Mauricio Samy Silva <xxx>
> 4:59 PM (6 hours ago)
> 
> to Vilmar, marinaflessa, emerson 
> Olá Vilmar,
> 
> Boa tarde.
> Nenhum incômodo.
> Lamentamos muito, mas entendemos que nem sempre as coisas saem como planejamos.
> Votos que tudo termine bem e havendo possibilidade de traduções no futuro entre em contato.
> 
> Obrigado pela valosa contribuição.
> Um grande abraço
> 
> Maurício "Maujor®" Samy Silva
> http://maujor.com
> twitter
> FaceBook
> 
> Conheça os livros do Maujor®, visite:
> http://livrosdomaujor.com.br
> 
> > De: Vilmar [mailto:vdaneto@inf.ufrgs.br] 
> > Enviada em: quarta-feira, 12 de outubro de 2016 12:06
> > Para: Mauricio Samy Silva <xxx>; marinaflessa@xxx
> > Cc: emerson@xxx
> > Assunto: Re: RES: Tradução de documentos - Railsgirlsguides
> > 
> > Olá Maujor,
> > 
> > A respeito dos documentos, ainda hoje estamos planejando entregar o bundler-development.md
> > Pode liberar para tradução os seguintes documentos:
> > 
> > 2014-05-10-ruby-atm.markdown
> > 
> > 2014-03-24-alternative-dev-environment.markdown
> > 
> > Estou enviando o e-mail apenas para não trancar a tradução para possíveis novos tradutores.
> > 
> > Peço desculpas se isto lhe causou algum incomôdo, mas ocorreram uns imprevistos. Estamos muito felizes em poder ajudar.
> > 
> > :)
> > 
> > [ ]s
