### ISSUE TITLE
Definição do logotipo inicial da WebIWG

### ISSUE THREAD

**Issue by devttt** [webiwg/webiwg-issues#5]
Tópico para discutirmos o logotipo inicial da WebIWG.

No futuro isso pode ser revisto, mas precisamos começar com algo mínimo e que não dê problemas, mesmo que seja bem simples.

**Comment by fititnt** [comment]
Por falta de designer no grupo e falta de tempo minha, eu por enquanto estou deixando como sugestão no grupo a gente usar simplesmente como logo o texto do nome da marca em azul com fonte Helvética.

Isso pode não ser bonito, mas definitivamente não é anti-profissional pra começarmos alguma coisa sem apelar pra banco de imagens com logos e dar problemas mais tarde.

![webiwg-logo](https://cloud.githubusercontent.com/assets/812299/18293789/671fc50a-746b-11e6-8a23-aadc8cfef894.png)

[webiwg-logo.psd.zip](https://github.com/webiwg/webiwg-issues/files/457949/webiwg-logo.psd.zip)
