### ISSUE TITLE
 Adicionar referência cruzada entre todos os sites da WebIWG

### ISSUE THREAD

**Issue by devttt** [webiwg/webiwg-issues#9]
Neste momento temos 3 projetos em andamento e o site da organização:
- http://acessibilidade.pt.webiwg.org/
- http://historia.pt.webiwg.org/ 
- http://eventos.webiwg.org/
- http://www.webiwg.org 

Esse tópico é para adicionar uma referência no rodapé de todos os sites dos demais projetos.

**Comment by rcgivisiez** [comment]
Novo projeto em http://glossario.pt.webiwg.org/. Ele também deve ser adicionado como referência cruzada em todos os sites da WebIWG

**Comment by robsmayer** [comment]
Também precisamos adicionar referência ao novo site das RFCs, link http://rfc.pt.webiwg.org/

**Comment by fititnt** [comment]
Adicionei apenas o RFC-PT. Pelo menos temporariamente, pode ser interessante deixar o glossário não ser referenciados nos demais sites até a gente ter um pouco mais de conteúdo nele. O RFC, por outro lado, já tem até a tradução RCF 2119.

Podem abrir e alterar esse tópico no futuro quando tivermos atualização dele, ou mesmo para adicionar o Glossário ou outro site.
